server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  level:
    root: info
    org.springframework.security: debug
    org.springdoc: debug
    org.hibernate.SQL: debug
    com.ootd.be: debug

jwt:
  access-token:
    expire-time: 30
  refresh-token:
    expire-time: 60

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json

spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:60001/ootd
    username: ootd
    password: ootd!@#123!@#

