server:
  servlet:
    context-path: /api
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  level:
    root: info
    org.springframework.security: debug
    org.springdoc: debug
    com.ootd.be: debug

jwt:
  access-token:
    expire-time: 30
  refresh-token:
    expire-time: 60

springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
